# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='auth_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
