# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20160520_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=None, upload_to=b'profile_pictures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(choices=[(b'CONSULTANT', b'Consultant'), (b'PARTNER', b'Partner')], default=None, max_length=40),
            preserve_default=False,
        ),
    ]
